### ISSUE TITLE
Color active votes in different shade of blue

### ISSUE THREAD

**Issue by dagurval** [dagurval/bip100.tech#1]
Currently both _passive_ and _active_ votes are colored blue in the vote table (see https://bip100.tech). 

_Passive_ meaning that there is no vote in the coinbase, thus the vote defaults to current limit. _Active_ meaning that there is a vote in the coinbase, such as bitcoin.com currently voting for 8MB with _/EB8/_.

We should have a different shade of blue for blocks with an active vote to visualize how many miners are voting.

@chaintip 365 days

**Comment by chaintip** [comment]
`0.01608291 BCH`| `~  10.27 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4vq25sc906xyn7ewqh4me0nuex9yeul37tfq) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/28), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by chaintip** [comment]
`0.01608291 BCH`| `~  14.38 USD` has now been claimed by @DJMcNab when pull request [#2](http://github.chaintip.org/dagurval/bip100.tech/pull/2) was merged.
